name: Build and Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # Backend Build
      # -------------------------
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        working-directory: ./Backend
        run: dotnet restore inventory.sln

      - name: Build
        working-directory: ./Backend
        run: dotnet build inventory.sln -c Release --no-restore

      - name: Publish API
        working-directory: ./Backend/InventoryApp.API
        run: dotnet publish -c Release -o publish

      # -------------------------
      # Frontend Build (Angular)
      # -------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install Angular dependencies
        working-directory: ./Frontend/inventory-app
        run: npm install

      - name: Build Angular App
        working-directory: ./Frontend/inventory-app
        run: npm run build -- --configuration production

      # -------------------------
      # SSH + Deployment
      # -------------------------
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Create target dirs on server
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo mkdir -p /var/www/inventoryapp_api"
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo mkdir -p /var/www/inventoryapp_frontend"
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo chown -R ${{ secrets.EC2_USER }}:$${{ secrets.EC2_USER }} /var/www"

      - name: Copy backend to server
        run: |
          rsync -avz ./Backend/InventoryApp.API/publish/ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/inventoryapp_api/

      - name: Copy Angular frontend to server
        run: |
          rsync -avz ./Frontend/inventory-app/dist/inventory-app/ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/inventoryapp_frontend/

      - name: Restart backend service
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart inventoryapp"
